# Configuración de Netlify para Taller Mecánico AutoMax

[build]
  # Directorio donde está el código fuente
  base = "/"
  
  # Comando de build
  command = "npm run build"
  
  # Directorio donde se genera el build
  publish = "build"

# Configuración de redirects para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y cache
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Variables de entorno (opcional)
[build.environment]
  CI = "false"  # Esto evita que los warnings se traten como errores
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

